version: '3.9'
services:
  application: 
    build: app-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      COUNTRY_CODE: id
    ports:
      -"8080:8080"
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose: 
      - "5432"
    ports:
      - "5432:5432"
    restart: always
